name: Azure Static Web Apps CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ['main']

permissions:
  contents: read
  pull-requests: write
  
env:
  NODEJS_VERSION: '24.x'

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    
    environment:
      name: ${{ github.event_name == 'push' && 'production' || 'staging' }}
      url: ${{ github.event_name == 'push' && 'https://microsoftgraveyard.com/' || steps.deploy.outputs.static_web_app_url }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      - name: Cache build
        uses: actions/cache@v5
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/src/WebClient/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci --prefix ./src/WebClient

      - name: Verify formatting
        run: npm run lint:ci --prefix ./src/WebClient

      - name: Build sources
        run: npm run build --prefix ./src/WebClient

      - name: Deploy static web app
        id: deploy
        uses: azure/static-web-apps-deploy@v1
        env:
          SKIP_DEPLOY_ON_MISSING_SECRETS: ${{ github.event_name == 'pull_request' }}
          IS_STATIC_EXPORT: true
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: './src/WebClient/out'
          skip_app_build: true
          skip_api_build: true

  close_pr:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request

    steps:
      - name: Close pull request
        id: closepullrequest
        uses: azure/static-web-apps-deploy@v1
        env:
          SKIP_DEPLOY_ON_MISSING_SECRETS: ${{ github.event_name == 'pull_request' }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN }}
          action: 'close'
          app_location: ''
